apiVersion: v1
kind: Service
metadata:
  labels:
    app: argoos
  name: argoos
  namespace: kube-system
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: argoos
  type: ClusterIP
